const { describe, test } = require('node:test')
const assert = require('node:assert')
const fs = require('fs')
const path = require('path')
const { ROOT, readJson } = require('./helpers/paths')

const pkg = readJson(path.join(ROOT, 'package.json'))
const builder = readJson(path.join(ROOT, 'electron-builder.json'))
const clientDir = path.join(ROOT, 'assets', 'client')
const clientPkg = readJson(path.join(clientDir, 'package.json'))

const exists = (rel) => fs.existsSync(path.join(ROOT, rel))
const installedVersion = (dir, name) => {
  const file = path.join(dir, 'node_modules', name, 'package.json')
  return fs.existsSync(file) ? readJson(file).version : null
}

describe('package.json', () => {
  test('version is semver', () => {
    assert.match(pkg.version, /^\d+\.\d+\.\d+(-[\w.]+)?$/)
  })

  test('main entry exists', () => {
    assert.ok(exists(pkg.main), pkg.main)
  })

  test('scripts reference files that exist', () => {
    for (const [name, script] of Object.entries(pkg.scripts)) {
      for (const [, file] of script.matchAll(/\bnode\s+([\w./-]+\.js)/g)) {
        assert.ok(exists(file), `script "${name}" runs missing ${file}`)
      }
    }
  })

  test('every runtime dependency is installed locally', () => {
    const missing = Object.keys(pkg.dependencies).filter((d) => !installedVersion(ROOT, d))
    assert.deepStrictEqual(missing, [], 'run npm install while online')
  })

  test('build tooling is installed locally', () => {
    for (const tool of ['electron', 'electron-builder', '@electron/asar', 'tailwindcss']) {
      assert.ok(installedVersion(ROOT, tool), `${tool} missing from node_modules`)
    }
  })
})

describe('electron-builder.json', () => {
  test('icons exist for every platform', () => {
    for (const platform of ['win', 'mac', 'linux']) {
      assert.ok(exists(builder[platform].icon), `${platform} icon ${builder[platform].icon}`)
    }
    assert.ok(exists(builder.nsis.installerIcon))
    assert.ok(exists(builder.nsis.uninstallerIcon))
  })

  test('nsis include script is generated by the build script', () => {
    const generator = fs.readFileSync(path.join(ROOT, 'scripts', 'generate-installer-script.js'), 'utf8')
    assert.ok(builder.nsis.include.endsWith('installer.nsh'))
    assert.match(generator, /installer\.nsh/)
    assert.match(pkg.scripts.build, /generate-installer-script\.js/)
  })

  test('nsis install dir matches the executable the installer kills', () => {
    const generator = fs.readFileSync(path.join(ROOT, 'scripts', 'generate-installer-script.js'), 'utf8')
    assert.ok(generator.includes(`Programs\\\\${builder.productName}"`), 'customInstDir does not match productName')
    assert.ok(generator.includes(`${builder.productName}.exe`), 'taskkill target does not match productName')
  })

  test('extraResources sources exist', () => {
    for (const res of builder.extraResources) {
      assert.ok(exists(res.from), res.from)
    }
  })

  test('dev-only and test folders are excluded from the app bundle', () => {
    for (const pattern of ['!build/**/*', '!scripts/**/*', '!plugins/**/*', '!assets/client/**/*', '!test/**/*']) {
      assert.ok(builder.files.includes(pattern), `files is missing ${pattern}`)
    }
  })

  test('publish target matches repository', () => {
    const repoUrl = pkg.repository.url.toLowerCase()
    assert.ok(repoUrl.includes(`${builder.publish.owner}/${builder.publish.repo}`.toLowerCase()), `${repoUrl} vs ${builder.publish.owner}/${builder.publish.repo}`)
  })
})

describe('game client (assets/client)', () => {
  test('main entry exists', () => {
    assert.ok(fs.existsSync(path.join(clientDir, clientPkg.main)), clientPkg.main)
  })

  test('dependencies are installed (npm run client:install)', () => {
    const missing = Object.keys(clientPkg.dependencies)
      .filter((d) => d !== 'strawberry-jam')
      .filter((d) => !installedVersion(clientDir, d))
    assert.deepStrictEqual(missing, [])
  })

  test('strawberry-jam self-link was removed so the asar does not embed the whole repo', () => {
    assert.ok(!fs.existsSync(path.join(clientDir, 'node_modules', 'strawberry-jam')))
  })

  test('contains no native .node modules (the patcher copies app.asar without .unpacked)', () => {
    const nativeModules = []
    const walk = (dir) => {
      for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, e.name)
        if (e.isDirectory()) walk(full)
        else if (e.name.endsWith('.node')) nativeModules.push(path.relative(clientDir, full))
      }
    }
    walk(clientDir)
    assert.deepStrictEqual(nativeModules, [])
  })
})
